name: Running tests
on:
  push:
permissions:
  contents: read
  actions: read
jobs:
  test-examples:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code 
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0  
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Install GCC
      run: sudo apt-get update && sudo apt-get install -y gcc
    
    - name: Test example 01-basic-build
      working-directory: ./tests
      run: |
        gcc base-test.c -o base-test
        ./base-test
        if [ $? -ne 0 ]; then
          echo "Base Test failed"
          exit 1
        fi
    
